# Create <finance-data>/compose.env for compose.yml: a fresh secret key, a login
# password (generated unless given), its Argon2id hash, and this machine's timezone.
#
#   pwsh deploy/init-env.ps1 -DataDir <finance-data>
#   pwsh deploy/init-env.ps1 -DataDir <finance-data> -Password '<chosen password>'
#
# Requires python with argon2-cffi (pip install argon2-cffi). compose.env holds
# secrets: it lives in the data directory and never in this repository.

[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$DataDir,
    [string]$Password
)

$ErrorActionPreference = 'Stop'
New-Item -ItemType Directory -Path $DataDir -Force | Out-Null
$data = (Resolve-Path -LiteralPath $DataDir).Path -replace '\\', '/'
$envPath = Join-Path $data 'compose.env'
if (Test-Path $envPath) {
    throw "$envPath already exists. Delete it first to regenerate credentials."
}

if (-not $Password) {
    $bytes = [byte[]]::new(18)
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    $Password = [Convert]::ToBase64String($bytes).TrimEnd('=')
}
if ($Password.Contains("'")) { throw 'The password must not contain a single quote.' }

$keyBytes = [byte[]]::new(32)
[System.Security.Cryptography.RandomNumberGenerator]::Fill($keyBytes)
$secretKey = [Convert]::ToBase64String($keyBytes)

# UTF-8 mode: Windows Python otherwise decodes piped text as the ANSI code page.
$hash = $Password | python -X utf8 -c @"
import sys
from argon2 import PasswordHasher
sys.stdout.write(PasswordHasher().hash(sys.stdin.read().rstrip('\n')))
"@
if (-not $hash -or $hash -notlike '`$argon2id`$*') {
    throw 'Failed to generate an Argon2id hash. Is argon2-cffi installed? (pip install argon2-cffi)'
}

$tz = [TimeZoneInfo]::Local.Id
$iana = $null
if ($IsWindows -and [TimeZoneInfo]::TryConvertWindowsIdToIanaId($tz, [ref]$iana)) { $tz = $iana }

# Single quotes stop Docker Compose from interpolating '$' in these values.
@"
# Generated by init-env.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm'). Secrets: never commit this file.
FINANCE_DATA=$data
TZ=$tz
WF_SECRET_KEY=$secretKey
WF_AUTH_PASSWORD_HASH='$hash'
WEALTHFOLIO_PASSWORD='$Password'
# Optional dead-man alert, for example https://hc-ping.com/<check-uuid>
# SYNC_PING_URL=
"@ | Set-Content -Path $envPath -Encoding utf8NoBOM

Write-Host "Wrote $envPath. Your Wealthfolio login password is WEALTHFOLIO_PASSWORD in that file." -ForegroundColor Green
