# Generate deploy/wealthfolio/.env with a fresh secret key and password hash.
#
#   pwsh ./init-env.ps1
#   pwsh ./init-env.ps1 -Password 'my chosen password'
#
# Requires: python with argon2-cffi  (pip install argon2-cffi)
# The generated .env is gitignored and must never be committed.

[CmdletBinding()]
param(
    [string]$Password,
    [string]$DataDir = 'D:/documents/finance-data/wealthfolio',
    [string]$BindAddr = '127.0.0.1',
    [int]$Port = 8088
)

$ErrorActionPreference = 'Stop'
$envPath = Join-Path $PSScriptRoot '.env'

if (Test-Path $envPath) {
    Write-Host ".env already exists at $envPath - not overwriting." -ForegroundColor Yellow
    Write-Host "Delete it first if you want to regenerate credentials."
    exit 1
}

# Generate a password if the caller did not supply one.
$generated = $false
if (-not $Password) {
    $bytes = [byte[]]::new(18)
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    $Password = [Convert]::ToBase64String($bytes).TrimEnd('=')
    $generated = $true
}

# 32 random bytes, base64, for WF_SECRET_KEY.
$keyBytes = [byte[]]::new(32)
[System.Security.Cryptography.RandomNumberGenerator]::Fill($keyBytes)
$secretKey = [Convert]::ToBase64String($keyBytes)

# Argon2id PHC hash of the password.
$hash = $Password | python -c @"
import sys
from argon2 import PasswordHasher
sys.stdout.write(PasswordHasher().hash(sys.stdin.read().rstrip('\n')))
"@

if (-not $hash -or $hash -notlike '`$argon2id`$*') {
    throw "Failed to generate an Argon2id hash. Is argon2-cffi installed? (pip install argon2-cffi)"
}

# Single-quote the hash so Docker Compose does not interpolate its '$' characters.
@"
# Generated by init-env.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm'). Never commit this file.
WF_DATA_DIR=$DataDir
WF_BIND_ADDR=$BindAddr
WF_PORT=$Port
WF_SECRET_KEY=$secretKey
WF_AUTH_PASSWORD_HASH='$hash'
WF_AUTH_TOKEN_TTL_MINUTES=60
"@ | Set-Content -Path $envPath -Encoding utf8

Write-Host "Wrote $envPath" -ForegroundColor Green

if ($generated) {
    # Write the password beside the database rather than echoing it into a
    # terminal transcript. Same trust domain as the data it protects.
    $pwFile = Join-Path $DataDir 'ADMIN-PASSWORD.txt'
    New-Item -ItemType Directory -Path $DataDir -Force | Out-Null
    @"
Wealthfolio login password, generated $(Get-Date -Format 'yyyy-MM-dd HH:mm').

    $Password

Move this into a password manager and delete this file.
Only the Argon2id hash is stored in .env; this plaintext exists solely so the
generated password is not lost.
"@ | Set-Content -Path $pwFile -Encoding utf8
    Write-Host "Generated password saved to: $pwFile" -ForegroundColor Cyan
    Write-Host "Move it to your password manager and delete that file." -ForegroundColor Cyan
}

Write-Host ""
Write-Host "Next:  docker compose -f `"$(Join-Path $PSScriptRoot 'compose.yml')`" up -d"
